### PR TITLE
docs: update toturial for IntelliJ IDEs

### PR DESCRIPTION
**Pull request by himself65**
Closes: #9

### CODE REVIEW

**Review by trivikr — APPROVED** [review]

**Comment by himself65** [comment]
This tutorial is broken after 1 year and I'm using a M2 macbook pro. Seems like there is an arch-related issue?

**Comment by legendecas** [comment]
> This tutorial is broken after 1 year and I'm using a M2 macbook pro. Seems like there is an arch-related issue?

@himself65 would you mind updating the PR? Or maybe we could merge this one if it is working for non-m-series users.

**Comment by himself65** [comment]
OK, I made it work again by another config

image

**Review by trivikr — APPROVED** [review]

**Pull request merged**
